### PR TITLE
Feature/add request code parameter in result

### PR DESCRIPTION
**Pull request by esunilkumare**
The Andorid method does have three parameters in the method onActivityResult: requestCode, resultCode and data.

> onActivityResult(int requestCode, int resultCode, Intent data

I have added the requestCode parameter to your project in this PR. Please review and merge if OK

### CODE REVIEW

**Comment by VictorAlbertos** [comment]
What is the use case for this PR? Why do you need to supply a request code?

**Comment by esunilkumare** [comment]
While starting an activity for result, we can pass requestCode as well. We do have third party libraries which call back the onActivityResult with a specific requestCode. Then the third party vendor expect their API be called after checking a specific requestCode and pass this requestCode back to them. This was our requirement.

However, I think it would be a generic requirement to have requestCode in the callback method's Result method as well

**Comment by VictorAlbertos** [comment]
@esunilkumare thanks for this PR. 

Do you mind updating the README file to reflect this change before merging?

**Comment by esunilkumare** [comment]
Thanks for your reply.
Updated README.MD file to reflect the requestCode usage.

**Pull request merged**
